Update requests to use httr::RETRY and harmonise verbose messages
ropensci/webchem pull request #271
Opened 2020-07-13 21:33 UTC by stitam

This PR addresses issues #257 and #268.

This PR updates most webservice requests to use `httr::RETRY()`. The main benefit is that it allows a webservice to be queried multiple times when the previous attempts was unsuccessful. This is especially useful when some webservices randomly become unavailable for a few seconds. Another benefit of the function is that it assigns HTTP status codes and status messages to all webservice requests, allowing harmonised verbose messages.

This PR is currently a draft. I will add new commits as I update each webservice.

Feel free to add a comment/review/suggest alternatives.

PR task list:
- [ ] Update NEWS
- [ ] Add tests (if appropriate)
- [ ] Update documentation with `devtools::document()`
- [ ] Check package passed

2020-08-31 21:29 UTC, stitam commented
Travis seems to ba failing due to a curl error

2020-08-31 21:33 UTC, stitam commented
Adding tests for verbose messages is quite time consuming so I'd prefer to add them in a separate PR after we decide we are happy with the current design.

2020-08-31 21:50 UTC, stitam commented
I didn't touch ChemSpider, because I figured the functions can be simplified quite a bit. It's already done but I'll open a separate PR for that.

2020-09-02 08:26 UTC, stitam commented
Travis is not working because Trusty is no longer supported, and I cannot get rJava to work under more recent versions. I'd rather let it go and fix Travis in a separate PR.

2020-09-07 08:14 UTC, andschar reviewed
PR looks nice! Some minor comments.

2020-09-07 19:36 UTC, stitam commented on R/chemid.R
> +      if(is.na(xml_find_first(ttt, "//h2[contains(., 'Physical Prop')]/following-sibling::div//table"))){
I see what you mean but I didn't edit this part. Maybe we should streamline this in a separate PR?

2020-09-07 19:49 UTC, stitam commented on R/ping.R
>        Sys.sleep(rgamma(1, shape = 5, scale = 1/10))
I am wondering if we would ever want to ping mulitple services in a function call. Maybe through `sapply()` when querying multiple databases? In that scenario, there may be value in keeping `Sys.sleep()`, what do you think?

2020-09-07 19:50 UTC, stitam commented on R/pubchem.R
>          return(NA)
Thanks for this, it's probably best to resolve it here.

2020-09-08 18:50 UTC, Aariq requested changes
I love love love `webchem_url()`, and `webchem_message()`, and I love that now **all** of the functions use the same `httr` style including the HTML status reporting.  Wonderful stuff.  However, for multiple queries I still think most users would prefer that a function fail quickly if a service is down, rather than going very slowly and returning many NAs.

If you decide to keep this behavior, however, there are a number of places where the function still errors when a service is down (tested by turning off wifi and running example). I think it almost always happens because some tidying step or row-binding step is expecting something other than a length 1, unnamed vector.  This could be fixed by returning a different data structure inside the `if (inherits(res, "try-error"))` statement.  Alternatively, you could wrap `foo()` in `try()` or use `purrr::possibly()` rather than wrapping `RETRY()` in `try()` inside of `foo()`.  So for example:

```
db_query <- function(query, verbose = TRUE) {

  foo <- function(query) {
    <function to do a single query.  Errors when service is down>
  }
  foo_safe <- possibly(foo, otherwise = tibble(query = NA, var1 = NA, var2 = NA), quiet = !verbose)
  out <- lapply(query, foo_safe)
}
```

2020-09-08 18:50 UTC, Aariq commented on R/pubchem.R
>              Sys.sleep(5 + rgamma(1, shape = 15, scale = 1 / 10))
The PUG-REST docs say "We ask that any script or application not make more than 5 requests per second, in order to avoid overloading the PubChem servers".  I don't think there's any reason to have a random delay here.  Should be `Sys.sleep(1/5)` or maybe `Sys.sleep(2/5)" to be safe?  Could handle in separate PR if there are other places where we can shorten delay based on published requirements (in API docs or robots.txt).

2020-09-08 18:50 UTC, Aariq commented on R/pubchem.R
> +      return(NA)
Returns a 2 x 0 tibble when service is down, not NAs. This is probably fine though.  Due to line 724 in `pc_extract()` which removes the only existing column when service is down.

2020-09-08 18:50 UTC, Aariq commented on R/wikidata.R
> +        return(NA)
errors anyways when service is down at line 112.  Might work if 
```suggestion
      if (inherits(res, "try-error")) {
        if (verbose) webchem_message("service_down")
        return(tibble(query = query, match = NA, wdid = NA)
```

2020-09-08 18:50 UTC, Aariq commented on R/wikidata.R
> +    if (inherits(res, "try-error")) {
Errors anyway when service is down.

2020-09-12 06:39 UTC, stitam commented on R/ping.R
>        Sys.sleep(rgamma(1, shape = 5, scale = 1/10))
Oh I see what you mean. I'll remove `Sys.sleep()`.

2020-09-14 14:50 UTC, andschar commented on R/pubchem.R
>          return(NA)
You mean here in this PR or there in #285? Sorry :)

2020-09-16 07:45 UTC, stitam commented on R/pubchem.R
>          return(NA)
Sorry, I meant in this PR. I've updated the function, it now returns the query strings in the `query` column.

```
get_cid(c('Triclosan', 'miau', '', NA), from = 'name')
Querying Triclosan. OK (HTTP 200).
Querying miau. Not Found (HTTP 404).
Querying . Not Found (HTTP 404).
Query is NA. Returning NA.
# A tibble: 4 x 2
  query       cid  
  <chr>       <chr>
1 "Triclosan" 5564 
2 "miau"      NA   
3 ""          NA   
4  NA         NA   
```

2020-09-16 08:45 UTC, andschar commented on R/pubchem.R
>          return(NA)
Great, thanks!

2020-09-17 06:29 UTC, stitam commented on R/alanwood.R
>      }
Good point, thanks @Aariq.

I added a line to the beginning of each query function. Now, when execution starts, they first check if the service is down and stop if it is. If not, then they start to query the compounds. Then, if there is a temporary service glitch during the queries, they print the "service_down" message, return `NA`, and continue with the queries.

I am wondering if there is value in the `try(RETRY()` structure afterall. If the service is really down, there is now a fast exit from the functions, but some services are just glitchy sometimes, and for those, the `try(RETRY()` structure would allow the function to run through with a few failures? I am ok to revert if we conclude `try(RETRY()` is not necessary afterall.

```
if (ping_service("aw") == FALSE) stop(webchem_message("service_down"))
```

2020-09-17 06:37 UTC, stitam commented on R/chebi.R
> +    }
Now that I added the line which stops the function in the beginning when the service is down, I expect `dplyr::select()` is unlikely to fail because at least one of the queries will be non `NA` and then the data structure of the output will be adequate, is this correct?

2020-09-17 06:43 UTC, stitam commented on R/cir.R
>    foo <- function(identifier, representation, resolver, first, verbose) {
I think it works because `first` is not used within `foo()`. But because of this bug, you can't really adjust `match`, it is fixed at `all`. I'd rather fix this in a separate PR, are you ok with that?

2020-09-17 06:51 UTC, stitam commented on R/pubchem.R
>              Sys.sleep(5 + rgamma(1, shape = 15, scale = 1 / 10))
Shall we fix this through issue #287?

2020-09-17 08:08 UTC, stitam commented on R/etox.R
>    out <- lapply(query, foo, from = from, match = match, verbose = verbose)
`lapply()` should return a list of tibbles here. The problem was caused by `return(NA)`:

```
 if (inherits(h, "try-error")) {
      if (verbose) webchem_message("service_down")
      return(NA)
    }
```

New version:

```
 if (inherits(h, "try-error")) {
      if (verbose) webchem_message("service_down")
      return(tibble::tibble("query" = query, "match" = NA, "etoxid" = NA))
    }
```

2020-09-17 08:08 UTC, stitam commented on R/cts.R
> +    if (inherits(res, "try-error")) {
Oh, it's because for cts even `match.arg()` uses the webservice. This should be fixed now by exiting the function in the very beginning.

2020-09-17 08:10 UTC, stitam commented on R/wikidata.R
> +    if (inherits(res, "try-error")) {
I added the `empty` object so that it doesn't error, but I think `wd_ident()` may need more discussion on what the output should look like.

2020-09-17 08:14 UTC, stitam commented on R/cts.R
>      }
You're right in that the function shouldn't query invalid inchikeys. In terms of a valid reason I can imagine when most of the inchikeys are valid but some are not? But I think these lines are not my edits, they were added earlier. I agree that we should discuss this with the other `is.*()` functions separately.

2020-09-17 08:18 UTC, stitam commented on R/chebi.R
> +    }
Should be fixed now through this:

```
if (inherits(res, "try-error")) {
      if (verbose) webchem_message("service_down")
      return(tibble::tibble("query" = query, "chebiid" = NA_character_))
    }
```

2020-09-17 08:28 UTC, stitam commented on R/pubchem.R
> +      return(NA)
That's a complex one. `pc_page()` returns `NA` and then `pc_extract()` fails to process the `NA` entry appropriately. It's definitely a bug, and will come up when the service is up, but glitchy. However, if you're ok with that I'd rather not fix it here but think about it later. Exiting the function early fixes the issue.

2020-09-17 13:13 UTC, Aariq commented on R/alanwood.R
>      }
This is great.  It's probably overkill to do `try(RETRY())`, but I think it's fine.  You're right that it will catch the edge case where a service goes down temporarily in the middle of a long list of queries, and I think that's important.

2020-09-17 13:14 UTC, Aariq commented on R/cir.R
>    foo <- function(identifier, representation, resolver, first, verbose) {
Yes, I can do it in a separate PR.  There are a couple of functions that can probably be switched over to use `matcher()` fairly easily.

2020-09-17 13:14 UTC, Aariq commented on R/pubchem.R
> +      return(NA)
Agreed!

2020-09-17 15:13 UTC, Aariq approved these changes

2020-09-17 15:30 UTC, merged