switch to use matcher() internally for handling match=
ropensci/webchem pull request #292
Opened 2020-09-20 21:31 UTC by Aariq

This PR closes #263 finally.  Switches `ci_query` and `pan_query` to use the `matcher()` utility internally.  These functions no longer return objects with a match distance attribute, as I didn't find that particularly useful and would have had to change `matcher()` to get it.

Minor change: `is.cas()` is now vectorized. 

**Question:**
Does `match = "best"` make sense for anything other than `from = "name"`?  I'm not sure it's even possible, but if a CAS number query returned multiple results `matcher()` would choose the best one by comparing the query (a CAS number) to the returned compound *names* using `adist()`. This is obviously wrong, and I could fix it to compare CAS query to CAS result.  However, I thought it didn't really make sense to compare CAS #s with `adist()`, so instead I just warn the user that `match = "best"` only makes sense for chemical names.

PR task list:
- [x] Update NEWS
- [x] Add tests (if appropriate)
- [x] Update documentation with `devtools::document()`
- [ ] Check package passed

2020-09-22 12:22 UTC, stitam requested changes
Thanks @Aariq for opening this PR, it looks good. Added a few notes.

2020-09-22 12:22 UTC, stitam commented on R/chemid.R
> +        hit_cas <- matcher(hit_cas, query = URLdecode(query), result = hit_names, match = match)
I am wondering if it would be worth to add the `verbose` argument to the `matcher()` call. I hope the verbose messages will print nicely:)

2020-09-22 12:22 UTC, stitam commented on R/chemid.R
> +      # handle multiple outputs
This is just a note, chemid is also doing two queries internally. It first coverts the query to cas and then queries the cas. It may be worth to atomise the functionality later.

2020-09-22 12:51 UTC, Aariq commented on R/chemid.R
> +  }
Good idea.  I can make this change.

2020-09-22 12:56 UTC, Aariq commented on R/chemid.R
> +                     match = c('first', 'best', 'ask', 'na'),
I don't like `match = match_options()` because then you can't see what the options are from tooltips or code completion. Also, not all functions currently support all the options for `match`.  It would make sense for the default to be the same across webchem.  I think the order should be "all", "best", "first", "ask", "na"  or "all", "first", "best", "ask", "na".  I'm not sure about vectorizing `match`---I think that's a separate issue maybe.

2020-09-22 12:59 UTC, Aariq commented on R/pan.R
> +      out <- as.list(ttt) #TODO: why not just keep it as a table???
I didn't necessarily mean to leave that there, but it was a good reminder!  `ttt` is a perfectly good rectangular piece of data and then line 128 just smashes it to bits!  Didn't want to mess with it here because it would change the output type and be a breaking change for `pan_query()`.

2020-09-22 13:04 UTC, Aariq commented on R/chemid.R
> +      # handle multiple outputs
Ok, I changed it back.  I understand what it means now.  As a note for a future improvement, if you query cas directly, does it only do the query once?  It seems like it still goes through both queries and shouldn't.

2020-09-22 14:49 UTC, stitam commented on R/chemid.R
> +                     match = c('first', 'best', 'ask', 'na'),
I see your point, not being able to see options from tooltips so I rest my case:) Agree, let's discuss vectorisation separately.

2020-09-22 14:50 UTC, stitam commented on R/pan.R
> +      out <- as.list(ttt) #TODO: why not just keep it as a table???
No, let's keep it there I just wasn't sure whether you wanted to start that discussion or not. I like it there, I don't mind the reminder.

2020-09-22 14:55 UTC, stitam commented on R/chemid.R
> +      # handle multiple outputs
Yes, I think it queries twice even for cas. I know I edited this function earlier, I am unsure if cas going throung both is my doing or not. I'll open an issue for it and we can look at it later.

2020-09-29 20:38 UTC, stitam approved these changes
Thanks @Aariq for the updates. Another win for consistency:)

2020-09-29 20:40 UTC, merged