fix ping_pubchem_pw() #335
ropensci/webchem pull request #336
Opened 2021-11-15 21:58 UTC by Aariq

Changes the URL used to check if PUG VIEW service is up (closes #335).  Also changes an expected response in test-pubchem.R (minor change in pubchem database entry).

PR task list:
- [x] Update NEWS
- [ ] Add tests (if appropriate)
- [ ] Update documentation with `devtools::document()`
- [x] Check package passed

2021-11-15 22:31 UTC, Aariq commented
So turns out Pubchem changed the name of the page with pKa on it, which is probably what caused all this.  One pubchem test is still failing, but it's not related to this change, I think.

2021-11-17 08:20 UTC, stitam requested changes

2021-11-17 08:20 UTC, stitam commented on R/ping.R
> +               "compound/176/JSON", sep = "/")
I wonder, will the function now query the whole page, and will this make it slower to ping the service? What do you think? On the other hand, I like that this change would make `ping_pubchem_pw()` robust to further changes in the structure of a PubChem page.

2021-11-17 08:20 UTC, stitam commented on tests/testthat/test-pubchem.R
> +  expect_equal(a[[3]], NA) #why was this expected to be NA?
Hard to believe sulfuric acid did not have pka values on PubChem but I do remember that all tests used to pass.. Anyway it is no longer NA so I think you can remove this test.

2021-11-17 08:20 UTC, stitam commented on DESCRIPTION
> +Version: 1.1.1.9003
Can you please bump it above 9004? I am guessing we started working on this issue at the same time :)

2021-11-17 18:48 UTC, Aariq commented on R/ping.R
> +               "compound/176/JSON", sep = "/")
It might be slightly slower, but I think its worth it to be less fragile.

2021-11-17 18:53 UTC, Aariq commented on DESCRIPTION
> +Version: 1.1.1.9003
Yeah, this was because the version in the NEWS file was different from that in the DESCRIPTION.  I used `usethis::use_version(which = "dev")` , in this PR, which handles both.  I'll bump it to 9004.

2021-11-17 19:06 UTC, Aariq commented on R/ping.R
> +               "compound/176/JSON", sep = "/")
Functions should only `ping()` once each time they're run, right?  The speed change should be minimal.

2021-11-19 10:48 UTC, sneumann commented
I can confirm that this branch installs on linux here and fixes our previously failing `pc_prop(96)` since the ping now succeeds. Thanks, yours, Steffen

2021-11-19 13:49 UTC, merged