Change `cir_query()` output to tibble #289
ropensci/webchem pull request #350
Opened 2022-02-15 16:33 UTC by Aariq

This changes the output of `cir_query()` to a tibble, a potentially breaking change for some.  Suggested in #289.  I also made a small fix to the `matcher()` utility so the query is printed when match = "ask".

PR task list:
- [x] Update NEWS
- [x] Add tests (if appropriate)
- [x] Update documentation with `devtools::document()`
- [x] Check package passed

2022-02-17 07:46 UTC, stitam requested changes
Thanks @Aariq for this PR, it looks good! One thing I noticed, when the query cannot be found in the database, the function returns `NA` in the query column as well (e.g. `cir_query("chemical", "cas")`). Do you see this on your end?

2022-02-17 14:07 UTC, Aariq commented
Yeah.  This was on purpose.  I think it's consistent with how the `get_*()` functions work?  It's useful for doing things like:

``` r
library(tidyverse)
library(webchem)
df <- tibble(cas = c("3380-34-5", NA, "56-40-6"))

df %>% 
  mutate(smiles = cir_query(cas, "smiles", match = "first")$smiles)

#> # A tibble: 3 × 2
#> cas       smiles                      
#> <chr>     <chr>                       
#>   1 3380-34-5 Oc1cc(Cl)ccc1Oc2ccc(Cl)cc2Cl
#> 2 NA        NA                          
#> 3 56-40-6   NCC(O)=O 
```

2022-02-18 09:48 UTC, stitam commented
Thanks @Aariq, I agree when the query is `NA` the output should include a row where the query column is also `NA`. But when the query is not `NA` but a string which cannot be found in the database, I think the functions should output the query string in the query column, like here:

``` r
webchem::get_cid(c("gentamycin", "pumpkin"))
#> # A tibble: 5 × 2
#>   query      cid      
#>   <chr>      <chr>    
#> 1 gentamycin 3467     
#> 2 gentamycin 72395    
#> 3 gentamycin 441305   
#> 4 gentamycin 132477936
#> 5 pumpkin    <NA>
```

<sup>Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

When I tested this with the new `cir_query()` I get `NA` in the query column as well: 

`cir_query(c("gentamycin", "pumpkin"), "smiles")`

```r
# A tibble: 2 × 2
  query      smiles                                                   
  <chr>      <chr>                                                    
1 gentamycin CNC(C)C1CCC(N)C(O1)OC2C(N)CC(N)C(OC3OCC(C)(O)C(NC)C3O)C2O
2 NA         NA  
```

2022-02-18 14:35 UTC, Aariq commented
Ooooh, gotcha.  I'll fix this.

2022-02-19 10:31 UTC, stitam approved these changes
Thanks @Aariq.

2022-02-19 10:31 UTC, stitam commented on R/cir.R
> +#' @return A tibble with a `query` column an a column for the requested representation.
```suggestion
#' @return A tibble with a `query` column and a column for the requested representation.
```

2022-02-19 10:56 UTC, merged