Functions for accessing a new database - ChEMBL
ropensci/webchem pull request #353
Opened 2022-03-29 09:46 UTC by stitam

This PR adds new functionality for accessing the ChEMBL database (https://www.ebi.ac.uk/chembl/). The database developers
created an API for retrieving the data (https://chembl.gitbook.io/chembl-interface-documentation/web-services), which I think evaluates to explicit consent to programmatic access, so we should be fine.

I would like to point out that I also added some caching functionality to `chembl_query()`. This was before Discussion #352. I am actively using this functionality, but I am OK to remove it if you think we should first discuss caching in more detail. Alternatively, I can merge this, implement other solutions with other webchem functions and then we can discuss/settle with one and update it everywhere. What do you think?

PR task list:
- [x] Update NEWS
- [x] Add tests (if appropriate)
- [x] Update documentation with `devtools::document()`
- [ ] Check package passed

2022-03-29 12:01 UTC, stitam commented
More info on licencing: https://chembl.gitbook.io/chembl-interface-documentation/about#chembl-team-members

2022-03-29 12:11 UTC, stitam commented
I have rerun the tests several times, `with_cts()` works on my end, I don't know why the ubuntu release version is not working..

2022-04-04 13:34 UTC, Aariq commented
I'm happy to review this, but it won't happen until next week at the earliest, FYI.  I'm excited to see how you made caching work!

2022-04-05 06:57 UTC, stitam commented
Thanks perfect, thanks @Aariq!

2022-09-21 20:41 UTC, Aariq commented
Hey, I just realized I never took a look at this.  I'll try and take a look sometime in the next few weeks

2022-09-22 07:15 UTC, stitam commented
No worries, thanks :)

2022-09-26 21:30 UTC, Aariq requested changes

2022-09-26 21:30 UTC, Aariq commented on R/chembl.R
> +#' \code{chembl_resources()} to see all available resources.
link to chembl_resources() help page
```suggestion
#' [chembl_resources()] to see all available resources.
```

2022-09-26 21:30 UTC, Aariq commented on R/chembl.R
> +  )
Any way to get this from the API?  Just trying to think ahead to when they add another resource

2022-09-26 21:30 UTC, Aariq commented on R/chembl.R
> +#' appropriate resource for a ChEMBL ID.
Can you add an example of how to do this?

2022-09-26 21:30 UTC, Aariq commented on R/chembl.R
> +atc_classes <- function(verbose = getOption("verbose"),
Should this be called `chembl_atc_classes()`?  Or is this something separate from ChEMBL?

2022-09-29 18:20 UTC, stitam commented on R/chembl.R
> +  )
So far I haven't found a way to get this from the API, but I can add at least one test for each resource. Though we won't notice when a new resource is added, but we will notice if any of the existing resources are changed/removed.

2022-09-29 18:32 UTC, stitam commented on R/chembl.R
> +atc_classes <- function(verbose = getOption("verbose"),
I wasn't sure because the ATC system itself is a general thing but you're right, the data set is queried from ChEMBL so it should be called `chembl_atc_classes()`, thanks.

2022-09-29 19:14 UTC, stitam commented on R/chembl.R
> +#' appropriate resource for a ChEMBL ID.
There is an example in the examples section but maybe it's not visible enough? I've updated the function documentation a bit, let me know if it's still not clear enough.

2022-09-29 20:27 UTC, Aariq commented on R/chembl.R
> +#' appropriate resource for a ChEMBL ID.
Yeah, looks good to me

2022-10-03 13:59 UTC, Aariq approved these changes

2022-10-03 17:51 UTC, merged