Return CAS number from nist_ri
ropensci/webchem pull request #379
Opened 2022-11-05 00:57 UTC by ethanbass

This PR contains implements suggested changes to the `nist_ri` function so that it returns an additional column containing the CAS number along with the other retention index information. Currently, if you use a query other than the CAS number, the function queries NIST for the CAS number and prints it to the console, but it is not recorded. It is especially useful to have the CAS number if you want to get multiple kinds of retention indices (e.g. kovats and alkane or polar and non-polar) for the same query. With the altered function, you can use the CAS number returned by the first query to request additional information, instead of querying NIST for the CAS number on each request.

PR task list:
- [x ] Update NEWS
- [ x] Add tests (if appropriate) (NA)
- [ x] Update documentation with `devtools::document()`
- [ x] Check package passed

2022-11-06 20:50 UTC, stitam requested changes
Many thanks @ethanbass for opening this PR! I agree it would be helpful to include cas in the function output. A new version of webchem has been released recently so I moved your NEWS entry up a little. I added a few comments, can you please resolve these?

2022-11-06 20:50 UTC, stitam commented on R/nist.R
> +    return(tibble(RI = NA, cas=attr(ri_xml, "cas")))
I am not sure about this one because:

``` r
nist_ri("balloon", verbose = TRUE)
#> Querying balloon. OK (HTTP 200).
#> Not available. Returning NA.
#> # A tibble: 1 × 2
#>   query   RI      cas   
#>   <chr>   <lgl>   <chr>
#> 1 balloon NA      balloon
```

I think in this case "cas" should also be NA, what do you think?

My other thought is just a matter of taste, I am wondering if it would look better if the table returned by `nist_ri()` contained first the query, then cas, then RI, then everything else? It feels tidier to start with identifiers

2022-11-06 20:50 UTC, stitam commented on R/nist.R
>        dplyr::select("RI", "type", "phase", everything())
My comment above may have an impact here as well.

2022-11-06 22:23 UTC, Aariq commented on R/nist.R
> +    return(tibble(RI = NA, cas=attr(ri_xml, "cas")))
Yeah, should be query, cas, RI I think.

2022-11-06 22:33 UTC, Aariq commented
It would be great to have tests for the following:

- a name query that returns a CAS number
- a name query for something without RI data, but that still has a CAS number (e.g. methane)
- a name query for something with RI data but without a CAS number, e.g. https://webbook.nist.gov/cgi/cbook.cgi?ID=R618870&Units=SI
- Is there any situation where a search for a CAS number would return a different CAS number? If that's a thing (honestly can't remember), we should have a test that that works correctly too maybe?

If you need help adding tests, let me know and I can help or point you toward examples

2022-11-07 15:36 UTC, ethanbass commented
Sounds good. I can try to write some tests. For scenario 2, the name that doesn't have RI data, (e.g. methane), this type of query will not return a CAS number at all the way the function is currently written. What do you all think the expected behavior should be here? I think the function would need to be significantly modified to make it return a cas number for this type of scenario.

For scenario 4, I can't think of an example where a cas number will return a different cas number, since as far as I can tell there aren't any records with more than one cas number. I'd be happy to try to implement this test if anyone has an example though.

2022-11-07 15:50 UTC, stitam commented on R/nist.R
> +    return(tibble(RI = NA, cas=attr(ri_xml, "cas")))
There is a helper function `is.cas()` in webchem that validates cas strings, maybe that could help?

2022-11-07 16:51 UTC, Aariq commented
> Sounds good. I can definitely try to write some tests. For scenario 2, the name that doesn't have RI data, (e.g. methane), this type of query will not return a CAS number at all the way the function is currently written. What do you all think the expected behavior should be here? I think the function would need to be significantly modified to make it return a cas number for this type of scenario.

I think returning `NA` is probably OK as long as it's clear in the function documentation that the CAS number will be returned *if and only if* RI data is found.


> For scenario 4, I can't think of an example where a cas number will return a different cas number, since as far as I can tell there aren't any records with more than one cas number. I'd be happy to try to implement this test if anyone has an example though.

I think you're probably right.  For some reason I was thinking NIST webbook redirected isomers or something, but played around with it a bit this morning and that doesn't seem to be the case.  Let's not worry about this

2022-11-09 15:46 UTC, ethanbass commented on R/nist.R
> +    return(tibble(RI = NA, cas=attr(ri_xml, "cas")))
I was thinking more about this. Do ya'll think it would make sense to have an additional logical argument (e.g. `validate_cas`)? If set to TRUE, the function could check that the CAS number is valid. If false, it will just assume that the CAS number is valid which is the current behavior. Could be still set to FALSE by default?

2022-11-09 19:46 UTC, Aariq commented
If I remember correctly, right now it's actually scraping the "large format table" (e.g. https://webbook.nist.gov/cgi/cbook.cgi?ID=C67561&Units=SI&Mask=2000&Type=LINEAR-RI-NON-POLAR-CUSTOM#LINEAR-RI-NON-POLAR-CUSTOM) and these have different row names (which get converted to column names by webchem).  If you can think of a good way to harmonize these tables then it would be nice to be able to combine them all into one output.  I.e. allow something like `nist_ri('67-56-1', type =  c("kovats", "linear"), polarity = c("polar", "non-polar"), temp_prog = "ramp")` to download RIs for kovats + polar, kovats + non-polar, linear + polar, and linear + non polar with a temperature ramp.  I think I previously decided against doing this because the tables have different info (e.g. T_start and T_end only appear in temperature ramp tables)

2022-11-10 09:29 UTC, stitam commented
I pushed  a commit that changes the following: 1. when we call `nist_ri()` to look up cas numbers, the function will stop with an error message if any query cas is invalid, before connecting to the webservice. I think stopping at input validation is not against our rules for handling input validation: once we start contacting the webservice, we don't want any queries to stop the process but before doing that I suppose it's finem do you agree @Aariq? 2. in the final output table the cas is now formatted appropriately (I looked at code comments within `is.cas()` to determine the rules).

2022-11-10 14:16 UTC, ethanbass commented
> I pushed a commit that changes the following: 1. when we call `nist_ri()` to look up cas numbers, the function will stop with an error message if any query cas is invalid, before connecting to the webservice. I think stopping at input validation is not against our rules for handling input validation: once we start contacting the webservice, we don't want any queries to stop the process but before doing that I suppose it's finem do you agree @Aariq? 2. in the final output table the cas is now formatted appropriately (I looked at code comments within `is.cas()` to determine the rules).

This is a cool idea! one potential issue I see, is that some of the record identifiers used by the NIST webbook don't seem to beactual CAS numbers, e.g. "R628941" -- one of the strings you use as an example for the new `format_cas` function . The most straightforward way to get records for E-longifolene is to provide this string as the cas number, but as far as I can tell isn't an actual cas number and will thus be rejected by the `is.cas` function. For example, if you run:
```
query <- webchem:::format_cas("R628941")
is.cas(query)
```
It returns FALSE, which will now cause the nist_ri function to error out.

2022-11-10 14:48 UTC, Aariq commented
>I pushed a commit that changes the following: 1. when we call nist_ri() to look up cas numbers, the function will stop with an error message if any query cas is invalid, before connecting to the webservice. I think stopping at input validation is not against our rules for handling input validation: once we start contacting the webservice, we don't want any queries to stop the process but before doing that I suppose it's finem do you agree @Aariq?

I don't think this is consistent with other webchem functions. I think we more commonly have the function not query the API / do the scraping, but continue to run and return `NA` for that particular query with a warning.  In the future, we could consider making this behavior optional with some kind of `stop_on_fail` option or argument.

>2. in the final output table the cas is now formatted appropriately (I looked at code comments within is.cas() to determine the rules).

Nice! There is an exported `as.cas()` function already though.  Please use that unless there is some reason it won't work in this case.

>This is a cool idea! one potential issue I see, is that some of the record identifiers used by the NIST webbook don't seem to be actual CAS numbers -- e.g. "R628941"

I feel like I've had this discussion before about the non-CAS identifiers on NIST, but I don't remember what we did and I can't find any issues about it!  I think they should get returned as-is probably, but it might be worthwhile learning more about what they are.

2022-11-10 14:48 UTC, Aariq commented on R/nist.R
> +}
can you use the already existing `as.cas()` instead?

2022-11-10 15:11 UTC, stitam commented on R/nist.R
> +}
Oh I forgot... sure!

2022-11-10 17:37 UTC, ethanbass commented
> If I remember correctly, right now it's actually scraping the "large format table" (e.g. https://webbook.nist.gov/cgi/cbook.cgi?ID=C67561&Units=SI&Mask=2000&Type=LINEAR-RI-NON-POLAR-CUSTOM#LINEAR-RI-NON-POLAR-CUSTOM) and these have different row names (which get converted to column names by webchem). If you can think of a good way to harmonize these tables then it would be nice to be able to combine them all into one output. I.e. allow something like `nist_ri('67-56-1', type = c("kovats", "linear"), polarity = c("polar", "non-polar"), temp_prog = "ramp")` to download RIs for kovats + polar, kovats + non-polar, linear + polar, and linear + non polar with a temperature ramp. I think I previously decided against doing this because the tables have different info (e.g. T_start and T_end only appear in temperature ramp tables)

Ya that's the type of syntax I had in mind as well. I think I have solution that will work for this. I'll try to finish it and push something soon.

2022-11-11 01:24 UTC, ethanbass commented
It was more complicated than I thought, but I think I figured out a pretty good way to implement the syntax with multiple arguments. One potential issue is that it now defaults to collecting all of the available retention index information, which puts more load on the server because it has to send a different query for each of the long format tables. I'm not sure if it would be better to set the default more restrictively? I also added some more tests of the types that you suggested @Aariq

2022-11-14 14:59 UTC, ethanbass commented
I saw that the tests failed, but as far as I can tell the failing tests aren't ones that I changed. Is this related to anything that i did? I think not. If so, I can try to look into it though

2022-11-14 15:52 UTC, Aariq commented
Failing tests are very possibly not your fault.  I'll take a closer look at this PR today or tomorrow and let you know if there are any other changes needed.  Thanks for putting a lot of thought into how this should work!

2022-11-14 18:04 UTC, stitam commented
Thanks @ethanbass! The tests pass locally on my computer as well so this is probably just a temporary glitch. I'll restart the tests in a bit.

2022-11-14 19:06 UTC, stitam requested changes
Thanks @ethanbass I see this PR grew quite a bit :D Thanks for improving the `format_cas()` function, I am now not sure it is needed at all :/ I have added a few comments, let me know what you think. Also feel free to add yourself as contributor.

2022-11-14 19:07 UTC, stitam commented on R/nist.R
> +}
@ethanbass updated the function and I added a comment there so I am going to mark this one as resolved.

2022-11-14 20:14 UTC, ethanbass commented on tests/testthat/test-nist.R
> +  expect_equal(test$cas, "U293031")
Yes, I wasn't too sure how to best deal with this. It's some kind of internal ID -- I don't really understand where these IDs come from. Usually they are the CAS number, but sometimes (as in this example) they're not. I'd be fine with just calling the column "nist_id" instead of "cas".

2022-11-14 20:19 UTC, ethanbass commented on tests/testthat/test-nist.R
> +                  temp_prog = "ramp", verbose=TRUE)
No I just left this in by accident. I'll fix it now

2022-11-14 21:22 UTC, ethanbass commented on R/nist.R
> +}
Personally I think it is cleaner and better to still have this as a separate function, but I agree that it should have the `noRd` tag. I will add it. It could also work to do the transformations on the spot, but it seems clunkier to me.

2022-11-14 21:28 UTC, ethanbass commented
> Thanks @ethanbass I see this PR grew quite a bit :D Thanks for improving the `format_cas()` function, I am now not sure it is needed at all :/ I have added a few comments, let me know what you think. Also feel free to add yourself as contributor.

Yes, I didn't quite realize what I was getting into... thanks for your suggestions! I went ahead and added myself to the description as suggested and resolved two of your comments. Still not quite sure what the best way is to deal with the weirdo CAS numbers. I'm think just changing the column name to `nist_id` might be the easiest/best approach, but i'm not sure

2022-11-15 00:45 UTC, ethanbass commented on tests/testthat/test-nist.R
> +  expect_equal(test$cas, "U293031")
One more thought on this-- it also would not be hard to split the difference and return two columns here -- one with the "nist_id" and one only with true CAS numbers, however, they would be mostly redundant with each other.

2022-11-15 15:50 UTC, Aariq requested changes
Got a chance to play around with this PR.  Very nice additions!  I have left some specific comments.

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +#' }
Let's show off the new feature in the example

```suggestion
#' myRIs <-
#'   nist_ri(
#'     c("78-70-6", "13474-59-4"),
#'     from = "cas",
#'     type = c("linear", "kovats"),
#'     polarity = "non-polar",
#'     temp_prog = "ramp"
#'   )
myRIs
```

2022-11-15 15:50 UTC, Aariq commented on tests/testthat/test-nist.R
>    expect_true(!anyNA(out$RI))
I think this test is a duplicate (of L17-22)  and can be removed

2022-11-15 15:50 UTC, Aariq commented on tests/testthat/test-nist.R
> +  expect_equal(test$cas, "U293031")
I don't think the user really needs to know the NIST internal IDs.  My opinion is that in this case the CAS should be `NA`.

2022-11-15 15:50 UTC, Aariq commented on tests/testthat/test-nist.R
> +})
I hate to ask for more tests (because our tests take _so_ long to run already), but it would be nice to see that all the expected columns are there.  So, like, the column names you get from a query with `temp_prog = c("ramp", "isothermal")` should be the column names from a query with `temp_prog = "ramp"` plus the column names from a query with `temp_prog = "isothermal"`.

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
I **love** this, but I think I'd like it to be a little _safer_.  I can't think of a real example, but if there was some compound named something like "deltatalone", this would incorrectly change it to "𝛿talone".  Maybe only do these replacements if they have non-letters next to them?

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +}
Should this just be in utils.R and get used for _everything_ @stitam?  Maybe as `webchem_try()` to be consistent with other helpers?

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +}
Definitely don't export this and include `@ noRd`.  Possibly change the name to `format_cas_nist` to avoid confusing future developers?

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +#'   will cause this function to run slower as CAS numbers are used as internal
Add something about how "alpha", "beta", etc. will automatically be converted to greek letters with `from = "name"`

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +    query <- format_cas(query)
why can't this just be `as.cas(query)`?

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +}
Also, this appears to do something unexpected with the name of the output. Very likely totally unimportant though.
```
as.cas("78706")
#   78-70-6 
# "78-70-6" 
format_cas("78706")
# 78706.78-70-6 
#     "78-70-6"
```

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +        # if cquery not found
```suggestion
        # if query not found
```

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
>      }
I like this approach!  I didn't get what `tables` was until running it in debug mode, but I see now that you're storing function arguments as rows of a matrix and iterating over rows.  Cool!

2022-11-15 15:50 UTC, Aariq commented on R/nist.R
> +  dplyr::mutate_at(vars(any_of(c("length", "diameter", "thickness", "temp",
I _think_ you don't need `vars()` anymore with dplyr 
```suggestion
  dplyr::mutate_at(any_of(c("length", "diameter", "thickness", "temp",
```

2022-11-15 18:12 UTC, ethanbass commented on R/nist.R
>  #' @param query query of type matching the options in `from`
Sorry I'm not sure what you're saying should be removed here?

2022-11-15 18:18 UTC, ethanbass commented on tests/testthat/test-nist.R
> +})
good idea. I will add this

2022-11-15 18:39 UTC, ethanbass commented on tests/testthat/test-nist.R
>    expect_true(!anyNA(out$RI))
yes, I noticed this too and almost removed it, but I didn't know if there was a reason. I will remove it now

2022-11-15 18:43 UTC, ethanbass commented on R/nist.R
> +    query <- format_cas(query)
the main reason was because I wanted to keep the weird nist_ids in there. I can probably remove the format_cas function if we don't want to do this

2022-11-15 19:34 UTC, ethanbass commented on R/nist.R
done, though i'm not sure my solution is the best or if there's a better way

2022-11-15 22:16 UTC, ethanbass commented on tests/testthat/test-nist.R
> +})
I added a new test for this: `test_that("nist_ri() works with multiple temperature program arguments"`

2022-11-16 15:46 UTC, Aariq commented on R/nist.R
>  #' @param query query of type matching the options in `from`
Oh, nevermind!  I didn't realize this was part of the documentation for the next function in the file.

2022-11-16 18:14 UTC, ethanbass commented
Oops, it looks like we inadvertently introduced a couple of typos with the last set of commits. i just pushed a fix

2022-11-16 18:20 UTC, ethanbass commented on R/nist.R
> +  dplyr::mutate_at(vars(any_of(c("length", "diameter", "thickness", "temp",
It looks like the `vars()` actually is still required. I am going to revert this commit

2022-11-16 20:33 UTC, Aariq commented on R/nist.R
> +  dplyr::mutate_at(vars(any_of(c("length", "diameter", "thickness", "temp",
`mutate_at()` is superseded, but it's fine to just leave it for now.  The "new" pattern is something like 
```
mutate(across(any_of(c("length", "diameter", "thickness", ...)),  as.numeric))
```

2022-11-16 20:55 UTC, ethanbass commented
Ah ok. I’m not really that up on the tidyverse syntax. It seems like it’s
always changing!

On Wed, Nov 16, 2022 at 3:33 PM Eric R. Scott ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In R/nist.R
> <https://github.com/ropensci/webchem/pull/379#discussion_r1024480640>:
>
> > +                           "phase" = "Active phase",
> +                           "length" = "Column length (m)",
> +                           "gas" = "Carrier gas",
> +                           "substrate" = "Substrate",
> +                           "diameter" = "Column diameter (mm)",
> +                           "thickness" = "Phase thickness (\u03bcm)",
> +                           "program" = contains("Program"),
> +                           "temp" = contains("Temperature (C)"),
> +                           "temp_start" = contains("Tstart (C)"),
> +                           "temp_end" = contains("Tend (C)"),
> +                           "temp_rate" = contains("Heat rate (K/min)"),
> +                           "hold_start" = contains("Initial hold (min)"),
> +                           "hold_end" = contains("Final hold (min)"),
> +                           "reference" = "Reference",
> +                           "comment" = "Comment") %>%
> +  dplyr::mutate_at(vars(any_of(c("length", "diameter", "thickness", "temp",
>
> mutate_at() is superseded, but it's fine to just leave it for now. The
> "new" pattern is something like
>
> mutate(across(any_of(c("length", "diameter", "thickness", ...)),  as.numeric))
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ropensci/webchem/pull/379#discussion_r1024480640>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADZEBOZISK2S47CNEGQF6DDWIVAKZANCNFSM6AAAAAARXVPBQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-16 21:06 UTC, Aariq commented
No worries.  `mutate_at()` isn't going anywhere anytime soon, so it's fine to leave it.

2022-11-16 21:22 UTC, ethanbass commented
Do you guys know why that test is always failing? It seems to work much more reliably on my laptop...

2022-11-16 21:46 UTC, stitam commented on R/nist.R
> +}
I looked at variations across the package: while this structure is quite common, we sometimes use "POST" instead of "GET" and we often have extra arguments, so I don't think we can use this function for everything. We could add an argument to adjust get/post and also add `...` to handle extra arguments, but I'm not sure if this makes it simpler or more complex. I also like the idea, maybe leave it here for now and resolve when we have thought a bit more about this?

2022-11-16 21:49 UTC, Aariq commented
CTS is just not very reliable, I think.  I'll re-run the failed tests.

2022-11-16 21:50 UTC, stitam approved these changes

2022-11-17 08:04 UTC, merged