Reformat cas
ropensci/webchem pull request #398
Opened 2023-05-08 16:46 UTC by ethanbass

- CAS numbers are automatically reformatted using `as.cas` in bcpc, cts, etox, flavornet, pan, pubchem, srs functions.
- Adds `verbose` argument to `as.cas`.
- Changes the behavior of `as.cas` so it returns a named character vector where names are the character strings from the original query.
- Alters test for `as.cas` (since it now retains the names of the original query).
- This pull request also changes the way names are assigned to `lapply` output because I ran into a problem with the way the output was being formatted for "non-cas" cas numbers like "balloon".
- Updated NEWS

PR task list:
- [ x] Update NEWS
- [ x] Add tests (if appropriate) [I didn't add any tests here, but let me know if you want me to add additional tests (e.g. that CAS numbers without dashes are being correctly reformatted).
- [x ] Update documentation with `devtools::document()`
- [ x] Check package passed

2023-05-08 20:41 UTC, Aariq requested changes
There are a few problems that need fixing, but the concept is great.

2023-05-08 20:41 UTC, Aariq commented on R/flavornet.R
> +    }
I think this should be moved up above line 39 so in the case that the CAS number isn't valid, and `as.cas()` returns `NA`, the website isn't queried

2023-05-08 20:41 UTC, Aariq commented on R/bcpc.R
> +      query <- as.cas(query, verbose = verbose)
It might be good to move this (or the whole `if (from == "cas")`) above line 57 so when the CAS number isn't valid and returns NA, the API isn't queried

2023-05-08 20:41 UTC, Aariq commented on R/cts.R
> +    if (from == "cas"){
Unless I'm mistaken, `cts_compinfo()` doesn't have an option for CAS numbers.  Anything other than `from = "inchikey"` should error.

2023-05-08 20:41 UTC, Aariq commented on R/cts.R
> +    if (from == "cas"){
Unless I'm mistaken, `cts_compinfo()` doesn't have an option for CAS numbers.  Anything other than `from = "inchikey"` should error.

2023-05-08 20:41 UTC, Aariq commented on R/cts.R
> +    if (from == "CAS"){
Should this be lowercase?
```suggestion
    if (from == "cas"){
```

2023-05-08 20:41 UTC, Aariq commented on R/etox.R
> +  names(query) <- query
The output of `get_etoxid` contains the formatted CAS number, not the original query, in the case of a CAS number without hyphens.  Should it be the original query for consistency with other functions?

2023-05-08 20:41 UTC, Aariq commented on R/pubchem.R
> +    if (from == "cas"){
"cas" isn't one of the options for `get_cid`, but maybe it should be.  Currently, you supply a CAS number with `from = "xref/rn"`.  You could make this work with the function as-is or add `"cas"` as an alias.

2023-05-08 23:07 UTC, ethanbass commented on R/cts.R
> +    if (from == "CAS"){
yes, it should. I got confused because I saw the upper case "CAS" in the documentation, but I see now that these arguments are converted to lower case inside the `match.arg`.

2023-05-08 23:09 UTC, ethanbass commented on R/flavornet.R
> +    }
good point.

2023-05-08 23:18 UTC, ethanbass commented on R/cts.R
> +    if (from == "cas"){
oops. you're right! i'll remove this

2023-05-08 23:18 UTC, ethanbass commented on R/bcpc.R
> +      query <- as.cas(query, verbose = verbose)
good point. I moved the whole thing up. Does that seem OK to you?

2023-05-08 23:28 UTC, ethanbass commented on R/etox.R
> +  names(query) <- query
I think this is generally true with the way i've implemented this, since i am overwriting the original query with the reformatted CAS numbers. (This is also the way that `nist_ri` is working in the current version). I'm not sure what would be a better alternative here?

2023-05-08 23:34 UTC, ethanbass commented on R/pubchem.R
> +    if (from == "cas"){
good point. I fixed this and added an "alias". I'm not sure if this needs to be documented? I'm finding the documentation for get_cid kind of confusing TBH, so I'm not really sure where this would go.

2023-05-09 12:48 UTC, ethanbass commented
> Thanks @ethanbass! Wondering if you folks want this to be part of the next release? I need to resubmit v1.3.0 to CRAN with some comments so I can wait until we merge this PR.

Whatever you all want to do in this regard is fine with me. I'm not really familiar with your release schedule

2023-05-09 13:52 UTC, Aariq requested changes

2023-05-09 13:52 UTC, Aariq commented on R/cts.R
>      }
Invalid cas numbers still aren't making it here for some reason,  e.g.

``` r
cts_convert('111111', "cas", "chemical name", verbose = TRUE)
# 111-11-1: Checksum is not correct! 5 vs. 1
# Querying NA. Error in strsplit(URL, "") : non-character argument

cts_convert(as.cas('111111'), "cas", "chemical name", verbose = TRUE)
# Query is NA. Returning NA.
# $<NA>
# [1] NA
```

The output of these two should be identical.  Might be good to write a test for this.

2023-05-09 13:52 UTC, Aariq commented on R/pubchem.R
> +    }
The other option, which I'm not sure is better, is to start a separate section with a `case_when()` or `switch()` or something to handle this, making it extendable to other "aliases".  I think I like the simpler solution for now.

2023-05-09 13:57 UTC, Aariq commented on R/etox.R
> +  names(query) <- query
`get_etoxid()` returns the formatted query
``` r
get_etoxid("34123596", from = "cas") # Isoproturon
## A tibble: 1 × 3
#  query      match       etoxid
#  <chr>      <chr>       <chr> 
# 1 34123-59-6 Isoproturon 7442  
```
But the way you've implemented this in the other functions, the original query is part of the returned object.  E.g. 

``` r
fn_percept("34123596")
# 34123596 
#      NA 
```
Should the output tibble have `"34123596"` or `"34123-59-6"` in the `query` column?

2023-05-09 14:01 UTC, Aariq commented on R/pubchem.R
> +    if (from == "cas"){
I would maybe edit the `@details` section (starting line 18) so that the rendered help file looks something like:

>Details
>Valid values for the from argument depend on the domain:
>- compound: "name", "smiles", "inchi", "inchikey", "formula", "sdf", "cas" (an alias for \"xref/RN"), \<xref\>, \<structure search\>, \<fast search\>.

2023-05-09 14:41 UTC, Aariq commented on R/pubchem.R
> +    }
Yeah, I think its good as is.  The more I think about it, it seems unlikely there will be a need for many other "aliases"

2023-05-09 16:06 UTC, ethanbass commented on R/etox.R
> +  names(query) <- query
we can overwrite the query using the `.id` argument in `bind_rows` (or add an additional column with the original query?): e.g. `out <- dplyr::bind_rows(out, .id = "query")`. I guess the question is what would be most desirable here?

2023-05-09 16:10 UTC, ethanbass commented on R/pubchem.R
> +    if (from == "cas"){
done

2023-05-09 16:11 UTC, ethanbass commented on R/cts.R
>      }
The only difference here for me is the name is NA in the second example, but I think this is the expected behavior?

2023-05-09 16:20 UTC, ethanbass commented on R/cts.R
>      }
Or do we want to somehow preserve the names here (if queries are given as a named character vector?) I guess there should be a way to do this, but it would complicate things.

2023-05-09 18:42 UTC, Aariq commented on R/cts.R
>      }
Ah, I must have been using an old commit or something.  Works now!

2023-05-09 18:44 UTC, Aariq commented on R/etox.R
> +  names(query) <- query
I would suggest just having the one `query` column and it should be whatever the user supplied (before `as.cas()`)

2023-05-09 19:11 UTC, stitam commented on R/etox.R
> +  names(query) <- query
I agree with keeping the original query: some users may want to use this variable for merging data; if we convert the queries automatically we may add unnecessary frustration. Whoever needs to convert the query column afterwards can always use `as.cas()`.

2023-05-09 20:03 UTC, ethanbass commented on R/etox.R
> +  names(query) <- query
OK sounds good. this is done in 56e357f

2023-05-09 20:11 UTC, ethanbass commented
Do we want to add additional tests associated with this PR?

2023-05-09 20:22 UTC, Aariq approved these changes

2023-06-02 06:01 UTC, stitam approved these changes

2023-06-02 06:26 UTC, stitam commented
Not sure why checks on ubuntu-20.04 (devel) passed before and do not pass now, maybe we should update GitHub actions? A possible lead here: https://community.rstudio.com/t/github-action-failure-with-rcmd-check-on-ubuntu-devel/129727. I'm going to merge this PR and fix the check afterwards.

2023-06-02 06:34 UTC, merged